# Linear Algebra

Solving a system $Ax = b$

In [1]:
import numpy as np
import scipy as sp
import scipy.linalg as splin

In [2]:
A = np.array([[1.0,1.0,1.0],[2.0,1.0,3.0],[3.0,1.0,6.0]])
print(A)

[[ 1.  1.  1.]
 [ 2.  1.  3.]
 [ 3.  1.  6.]]


In [3]:
b = np.array([4.0,7.0,2.0])
print(b)

[ 4.  7.  2.]


In [4]:
x = np.linalg.solve(A,b)
print(x)

[ 19.  -7.  -8.]


Matrix Factorization: LU decomposition

In [5]:
A = np.array([[1.0,1.0,1.0],[2.0,1.0,3.0],[3.0,1.0,6.0]])
print(A)

[[ 1.  1.  1.]
 [ 2.  1.  3.]
 [ 3.  1.  6.]]


In [6]:
P,L,U = splin.lu(A)
print("P matrix")
print(P)
print("L matrix")
print(L)
print("U matrix")
print(U)

P matrix
[[ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]]
L matrix
[[ 1.          0.          0.        ]
 [ 0.33333333  1.          0.        ]
 [ 0.66666667  0.5         1.        ]]
U matrix
[[ 3.          1.          6.        ]
 [ 0.          0.66666667 -1.        ]
 [ 0.          0.         -0.5       ]]


Solving $Ax = b$ using LU decompositon:  
$Ax = b \Rightarrow PLUx = b$   
Solve the following in sequence:   
$Py_1 = b$   
$Ly_2 = y_1$   
$Ux = y_2$   

In [7]:
b = np.array([4.0,7.0,2.0])
y1 = np.linalg.solve(P,b)
y2 = np.linalg.solve(L,y1)
x = np.linalg.solve(U,y2)
print(x)

[ 19.  -7.  -8.]


Matrix Factorization: Cholesky Factorization  
$A = LL^T$

In [8]:
A = np.array([[2.0,1.0,1.0],[1.0,4.0,2.0],[1.0,2.0,6.0]])
print(A)

[[ 2.  1.  1.]
 [ 1.  4.  2.]
 [ 1.  2.  6.]]


In [9]:
R = splin.cholesky(A)
print(R)

[[ 1.41421356  0.70710678  0.70710678]
 [ 0.          1.87082869  0.80178373]
 [ 0.          0.          2.20389266]]


In [10]:
print(np.dot(R.transpose(),R))

[[ 2.  1.  1.]
 [ 1.  4.  2.]
 [ 1.  2.  6.]]


Solve $Ax=b$ using cholesky factorization  
$Ax = b \Rightarrow R^TRx = b$  
Solve $R^Ty = b$  
Solve $Rx = y$  

In [11]:
b = np.array([7,15,23])
y = np.linalg.solve(R.transpose(),b)
x = np.linalg.solve(R,y)
print(x)

[ 1.  2.  3.]


## Example: Modeling a Separation System

The set of mass balances are:
\begin{align}
x_1 + x_2 + x_3 & = 10 \\
0.04x_1 + 0.54x_2 + 0.26x_3 & = 2 \\
0.93x_1 + 0.24x_2 + 0.0x_3 & = 6
\end{align}

In [12]:
A = np.array([[1.0,1.0,1.0],[0.04,0.54,0.26],[0.93,0.24,0.0]])
b = np.array([10.0,2.0,6.0])
x = np.linalg.solve(A,b)
print(x)

[ 5.82375479  2.43295019  1.74329502]
